services:
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/brainbytes
    command: bun run dev
    volumes:
      - ./packages/backend:/app
      - /app/node_modules

  frontend:
    ports:
      - "3000:3000"
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
      - /app/.next

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=brainbytes

volumes:
  postgres_data:
