version: "3.8"

services:
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    command: bun run dev
    volumes:
      - ./packages/backend:/app
      - /app/node_modules

  frontend:
    ports:
      - "3000:3000"
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: npm run dev
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
      - /app/.next
