/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    BetterAuthSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    BrainbytesApp: {
      type: "sst.aws.Nextjs";
      url: string;
    };
    CloudflareAccountId: {
      type: "sst.sst.Secret";
      value: string;
    };
    CloudflareApiToken: {
      type: "sst.sst.Secret";
      value: string;
    };
    DatabaseUrl: {
      type: "sst.sst.Secret";
      value: string;
    };
    GithubClientId: {
      type: "sst.sst.Secret";
      value: string;
    };
    GithubClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientId: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    OpenaiApiKey: {
      type: "sst.sst.Secret";
      value: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
